#DESENVOLVIMENTO ===========================================================
DEVELOPER:
    HOST: 'localhost'
    DOMAIN: dev
    IP_SERVER_IMAGE: '10.100.200.100'
    
    DATABASE_NAME: 'hospital_api'
    
    DB_SYSTEM: 'mysql'
    
    DB_BOOTSTRAP_HOST: 'mysql'
    DB_BOOTSTRAP_USER: 'root'
    DB_BOOTSTRAP_PASSWORD: 'root'
    DB_BOOTSTRAP_DRIVER: 'pdo_mysql'

    DB_APPLICATION_HOST: 'mysql'
    DB_APPLICATION_USER: 'root'
    DB_APPLICATION_PASSWORD: 'root'
    DB_APPLICATION_DRIVER: 'pdo_mysql'

    AD: false
    AD_HOST: 'ldap://10.100.1.10'
    AD_USER: 'servweb'
    AD_PASSWORD: 'hu@esc@gamp@web'
    AD_DOMAIN: '@hmd.local'

    DEBUG_ACTIVE: true
    DEBUG_EMAIL: 'gustavo.soares@gampcanoas.com.br'

    USERTEST_ID: 'gustavo.soares'
    USERTEST_PWD: 'gustavoti'
    USERTEST_NAME: 'Gustavo Ferreira Soares'
    USERTEST_LEVEL: '1'
    USERTEST_GROUP: 'TECNOLOGIA DA INFORMACAO HU'
    USERTEST_OCCUPATION: "Assistente de sistemas"

    EMAIL_DEFAULT_EMAIL: 'anonimo.gampcanoas@gmail.com'
    EMAIL_DEFAULT_PASSWORD: 'g4mpcanoas'
    EMAIL_DEFAULT_HOST: 'gmail'
    EMAIL_DEFAULT_NAME: 'Anônimo'
    
#DESENVOLVIMENTO - WINDOWS ==============================================
DEVWIN:
    HOST: 'localhost'
    IP_SERVER_IMAGE: '10.100.200.100'
    DOMAIN: win
    
    DATABASE_NAME: 'intra2_dev'

    DB_SYSTEM: 'mysql'
    
    DB_BOOTSTRAP_HOST: 'localhost'
    DB_BOOTSTRAP_USER: 'root'
    DB_BOOTSTRAP_PASSWORD: 'root'
    DB_BOOTSTRAP_DRIVER: 'pdo_mysql'

    DB_APPLICATION_HOST: 'localhost'
    DB_APPLICATION_USER: 'root'
    DB_APPLICATION_PASSWORD: 'root'
    DB_APPLICATION_DRIVER: 'pdo_mysql'
    
    AD: true
    AD_HOST: 'ldap://10.100.1.10'
    AD_USER: 'servweb'
    AD_PASSWORD: 'hu@esc@gamp@web'
    AD_DOMAIN: '@hmd.local'
    
    DEBUG_ACTIVE: true
    DEBUG_EMAIL: 'gustavo.soares@gampcanoas.com.br'
    
    EMAIL_DEFAULT_EMAIL: 'anonimo.gampcanoas@gmail.com'
    EMAIL_DEFAULT_PASSWORD: 'g4mpcanoas'
    EMAIL_DEFAULT_HOST: 'gmail'
    EMAIL_DEFAULT_NAME: 'Anônimo'

#HOMOLOGAÇÃO ===============================================================
HOMOLOG:
    HOST: '10.100.200.100'
    IP_SERVER_IMAGE: '10.100.200.100'
    DOMAIN: homo
    
    DATABASE_NAME: 'intra2_homo'
    
    DB_SYSTEM: 'mysql'
    
    DB_BOOTSTRAP_HOST: '10.100.1.33'
    DB_BOOTSTRAP_USER: 'dev'
    DB_BOOTSTRAP_PASSWORD: 'devloop356'
    DB_BOOTSTRAP_DRIVER: 'pdo_mysql'

    DB_APPLICATION_HOST: '10.100.1.33'
    DB_APPLICATION_USER: 'homo'
    DB_APPLICATION_PASSWORD: 'homolog123'
    DB_APPLICATION_DRIVER: 'pdo_mysql'

    AD: true
    AD_HOST: 'ldap://10.100.1.10'
    AD_USER: 'servweb'
    AD_PASSWORD: 'hu@esc@gamp@web'
    AD_DOMAIN: '@hmd.local'
    
    DEBUG_ACTIVE: false
    DEBUG_EMAIL: 'gustavo.soares@gampcanoas.com.br'

    EMAIL_DEFAULT_EMAIL: 'anonimo.gampcanoas@gmail.com'
    EMAIL_DEFAULT_PASSWORD: 'g4mpcanoas'
    EMAIL_DEFAULT_HOST: 'gmail'
    EMAIL_DEFAULT_NAME: 'Anônimo'
    
#PRODUÇÃO ==================================================================
PRODUCTION:
    HOST: '10.100.1.32'
    IP_SERVER_IMAGE: '10.100.1.117'
    DOMAIN: prod
    
    DATABASE_NAME: 'intra2'
        
    DB_SYSTEM: 'mysql'
    
    DB_BOOTSTRAP_HOST: '10.100.1.33'
    DB_BOOTSTRAP_USER: 'dev'
    DB_BOOTSTRAP_PASSWORD: 'devloop356'
    DB_BOOTSTRAP_DRIVER: 'pdo_mysql'

    DB_APPLICATION_HOST: '10.100.1.33'
    DB_APPLICATION_USER: 'prod'
    DB_APPLICATION_PASSWORD: 'prod362'
    DB_APPLICATION_DRIVER: 'pdo_mysql'

    AD: true
    AD_HOST: 'ldap://10.100.1.10'
    AD_USER: 'servweb'
    AD_PASSWORD: 'hu@esc@gamp@web'
    AD_DOMAIN: '@hmd.local'
    
    DEBUG_ACTIVE: false
    DEBUG_EMAIL: 'gustavo.soares@gampcanoas.com.br'

    EMAIL_DEFAULT_EMAIL: 'anonimo.gampcanoas@gmail.com'
    EMAIL_DEFAULT_PASSWORD: 'g4mpcanoas'
    EMAIL_DEFAULT_HOST: 'gmail'
    EMAIL_DEFAULT_NAME: 'Anônimo'

