<?php

use HospitalApi\Entity\OmbudsmanDemands;
use HospitalApi\Model\OmbudsmanDemandsModel;

$model = new OmbudsmanDemandsModel();

if(!$model->findBy()){
    $Demands = [
        ["name" => "Agressão Fisica"],
        ["name" => "Alimentação"],
        ["name" => "Alimentação Fria"],
        ["name" => "Atendimento"],
        ["name" => "Atendimento Prioritário"],
        ["name" => "Atendimento Restrito"],
        ["name" => "Cancelamento de Cirurgia"],
        ["name" => "Cancelamento de Cirurgia sem Aviso Prévio"],
        ["name" => "Cancelamento de Consulta"],
        ["name" => "Cancelamento de Exame"],
        ["name" => "Cancelamento de Exame sem aviso Prévio"],
        ["name" => "Cardápio"],
        ["name" => "Cirurgia Bariátrica"],
        ["name" => "Cirurgia Bucomaxilofacial"],
        ["name" => "Cirurgia Cabeça e Pescoço"],
        ["name" => "Cirurgia Cardiologica"],
        ["name" => "Cirurgia Cardiologia Pediátrica"],
        ["name" => "Cirurgia Geral"],
        ["name" => "Cirurgia Pediatrica"],
        ["name" => "Cirurgia Plástica"],
        ["name" => "Cirurgia Torácica"],
        ["name" => "Cirurgia Traumatologica"],
        ["name" => "Cirurgia Urologista"],
        ["name" => "Cirurgia Vascular"],
        ["name" => "Conduta Enfermagem"],
        ["name" => "Conduta Médica"],
        ["name" => "Consulta"],
        ["name" => "Consulta Cardiologista"],
        ["name" => "Consulta Cardiovascular"],
        ["name" => "Consulta Cirurgião Bucomaxilofacial"],
        ["name" => "Consulta Cirurgião Cardíaco"],
        ["name" => "Consulta Cirurgião Geral"],
        ["name" => "Consulta Cirurgião Plástico"],
        ["name" => "Consulta Cirurgião Toráxico"],
        ["name" => "Consulta Cirurgião Vascular"],
        ["name" => "Consulta Clinico Geral"],
        ["name" => "Consulta Dermatologista"],
        ["name" => "Consulta Endocrinologista"],
        ["name" => "Consulta Fisioterapia"],
        ["name" => "Consulta Ginecologista"],
        ["name" => "Consulta Gastrologista"],
        ["name" => "Consulta Geriatra"],
        ["name" => "Consulta Ginegologista"],
        ["name" => "Consulta Hematologista"],
        ["name" => "Consulta Infectologista Pediatria"],
        ["name" => "Consulta Nefrologista"],
        ["name" => "Consulta Neurologista"],
        ["name" => "Consulta Neuro Cirurgião"],
        ["name" => "Consulta Neuro Pediatra"],
        ["name" => "Consulta Nutricionista"],
        ["name" => "Consulta Oftalmologista"],
        ["name" => "Consulta Otorrinolaringologista"],
        ["name" => "Consulta Ortopedista"],
        ["name" => "Consulta Pediatra"],
        ["name" => "Consulta Pneumologista"],
        ["name" => "Consulta Pneumologista Pediatrico"],
        ["name" => "Consulta Psicólogo"],
        ["name" => "Consulta Psiquiatra"],
        ["name" => "Consulta Reumatologista"],
        ["name" => "Consulta Traumatologista"],
        ["name" => "Consulta Traumatologista Infantil"],
        ["name" => "Consulta Urologista"],
        ["name" => "Consulta Vascular"],
        ["name" => "Demora Atendimento"],
        ["name" => "Entrega de Exames"],
        ["name" => "Eletrocardiograma"],
        ["name" => "Exame"],
        ["name" => "Exame Arteriografia"],
        ["name" => "Exame Audiometria"],
        ["name" => "Exame Biopsia"],
        ["name" => "Exame Cateterismo"],
        ["name" => "Exame Colonoscopia"],
        ["name" => "Exame CPRE"],
        ["name" => "Exame Densitometria"],
        ["name" => "Exame Ecografia"],
        ["name" => "Exame Eletroencefalograma em Sono e Vigília"],
        ["name" => "Exame Eletroneuromiografia"],
        ["name" => "Exame Endoscopia"],
        ["name" => "Exame Espirometria"],
        ["name" => "Exame Fibrobronscopia"],
        ["name" => "Exame Laboratorial"],
        ["name" => "Exame Mamografia"],
        ["name" => "Exame Manometria"],
        ["name" => "Exame Ressonancia Magnética"],
        ["name" => "Exame RX"],
        ["name" => "Exame Tomografia"],
        ["name" => "Falta de Cadeira de Rodas"],
        ["name" => "Fisioterapia"],
        ["name" => "Infraestrutura"],
        ["name" => "Insuficiente"],
        ["name" => "Laudo de Exames"],
        ["name" => "Postura Atendimento"],
        ["name" => "Postura Higienização"],
        ["name" => "Postura Nutrição"],
        ["name" => "Postura Recepção"],
        ["name" => "Postura Segurança"],
        ["name" => "Postura Enfermagem"],
        ["name" => "Postura Médica"],
        ["name" => "SAME - Atrazo na Entrea do prontuário"],
        ["name" => "SAME - Prontuario"],
        ["name" => "Telefonia"],
        ["name" => "Transporte"],
        ["name" => "Troca de Leito"],
        ["name" => "Troca de Lençol"],
    ];
    
    foreach ($Demands as $demand) {
        $Demand = new OmbudsmanDemands();
        $Demand->setName($demand['name']);
        $model->doInsert($Demand);
    }
    echo "Demand Inserted\n";
} else {
    echo "Demand was ignored\n";
}
        