<?php

use HospitalApi\Entity\Sector;
use HospitalApi\Model\SectorModel;

$model = new SectorModel();

$sectors = [
    // ["name" => "ADMINISTRAÇÃO HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "UNIDADE ADULTO 1 HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "UNIDADE ADULTO 2 HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "SERVIÇO SOCIAL HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "SERVIÇO APOIO AO CLIENTE HPSC",	    "enterpriseId" => "hpsc"],
    // ["name" => "SECRETARIA MUNICIPAL SAÚDE HPS",	"enterpriseId" => "hpsc"],
    // ["name" => "ENDOSCOPIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "SALA DE RECUPER INTERNADO HPSC",	"enterpriseId" => "hpsc"],
    // ["name" => "E.C.G HPSC",	                    "enterpriseId" => "hpsc"],
    // ["name" => "FISIOTERAPIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "PRONTO ATEND. PEDIÁTRICO HPSC",	    "enterpriseId" => "hpsc"],
    // ["name" => "FATURAMENTO HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "TELEFONIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "RECEPÇÕES HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "SERVIÇO DE PSICOLOGIA HPSC",	    "enterpriseId" => "hpsc"],
    // ["name" => "RECURSOS HUMANOS HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "TECNOLOGIA DA INFORMAÇÃO HPSC",	    "enterpriseId" => "hpsc"],
    // ["name" => "TRANSPORTE HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "S.C.I.H HPSC",	                    "enterpriseId" => "hpsc"],
    // ["name" => "S.A.M.E HPSC",	                    "enterpriseId" => "hpsc"],
    // ["name" => "UPA - CAÇAPAVA HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "UPA - RIO BRANCO HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "PATOLOGIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "SEDE GAMP - CENTRO",	            "enterpriseId" => "hpsc"],
    // ["name" => "SAMU",	                            "enterpriseId" => "hpsc"],
    // ["name" => "SEGURANCA PATRIMONIAL",	            "enterpriseId" => "hpsc"],
    // ["name" => "AMBULATÓRIO HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "AGÊNCIA TRANSFUSIONAL HPSC",	    "enterpriseId" => "hpsc"],
    // ["name" => "HOSPITAL UNIVERSITÁRIO HPSC",	    "enterpriseId" => "hpsc"],
    // ["name" => "S.E.S.M.T HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "SUPRIMENTOS HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "FARMÁCIA HPSC",	                    "enterpriseId" => "hpsc"],
    // ["name" => "GOVERNANÇA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "ROUPARIA HPSC",	                    "enterpriseId" => "hpsc"],
    // ["name" => "MANUTENÇÃO HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "NUTRIÇÃO HPSC",	                    "enterpriseId" => "hpsc"],
    // ["name" => "CLINICA MÉDICA HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "CENTRO CIRÚRGICO HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "UNIDADE ADULTO 3 HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "CTI ADULTO HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "EMERGÊNCIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "ECOGRAFIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "LABORATÓRIO HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "RADIOLOGIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "TOMOGRAFIA HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "PACIENTE INTERNO HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "PACIENTE EXTERNO HPSC",	            "enterpriseId" => "hpsc"],
    // ["name" => "S.E.G.E.R HPSC",	                "enterpriseId" => "hpsc"],
    // ["name" => "C.M.E HPSC",	                    "enterpriseId" => "hpsc"],
    // ["name" => "S.E.S.M.T HU",	                    "enterpriseId" => "hu"],
    // ["name" => "UNID. INTERNAÇÃO 9º ANDAR HU",	    "enterpriseId" => "hu"],
    // ["name" => "RECEPÇÕES HU",	                    "enterpriseId" => "hu"],
    // ["name" => "SCIH - SERV CONT INF HU",	        "enterpriseId" => "hu"],
    // ["name" => "C.M.E HU",	                        "enterpriseId" => "hu"],
    // ["name" => "AMB. SAÚDE AUDITIVA HU",	        "enterpriseId" => "hu"],
    // ["name" => "RESTAURANTE HU",	                "enterpriseId" => "hu"],
    // ["name" => "CENTRO DE ENSINO E PESQUISA",	    "enterpriseId" => "hu"],
    // ["name" => "CENTRAL DE LEITOS HU",	            "enterpriseId" => "hu"],
    // ["name" => "ESPIROMETRIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "CAPS - NOVOS TEMPOS HU",	        "enterpriseId" => "hu"],
    // ["name" => "CAPS - AMANHECER HU",	            "enterpriseId" => "hu"],
    // ["name" => "CAPS - RECANTO DOS GIRASSÓIS",	    "enterpriseId" => "hu"],
    // ["name" => "CAPS - TRAVESSIA HU",	            "enterpriseId" => "hu"],
    // ["name" => "UNID. CUIDADOS ESPECIAIS",	            "enterpriseId" => "hu"],
    // ["name" => "CENTRO DE PESQUISA CLÍNICA HU",	    "enterpriseId" => "hu"],
    // ["name" => "SERVIÇO DE PSICOLOGIA HU",	        "enterpriseId" => "hu"],
    // ["name" => "SERVIÇO SOCIAL HU",	                "enterpriseId" => "hu"],
    // ["name" => "UPA - CAÇAPAVA HU",	                "enterpriseId" => "hu"],
    // ["name" => "UPA - RIO BRANCO HU",	            "enterpriseId" => "hu"],
    // ["name" => "HOSP PRONTO SOCORRO CANOAS HU",	    "enterpriseId" => "hu"],
    // ["name" => "AMB. GEST. DE ALTO RISCO HU",	    "enterpriseId" => "hu"],
    // ["name" => "CENTRO CIRÚRGICO AMB. HU",	        "enterpriseId" => "hu"],
    // ["name" => "SEGURANÇA PATRIMONIAL",	            "enterpriseId" => "hu"],
    // ["name" => "UNID. INTERNAÇÃO hpscº ANDAR HU",	"enterpriseId" => "hu"],
    // ["name" => "UNID. INTERN.hpscº A - RETAGUARDA",	"enterpriseId" => "hu"],
    // ["name" => "UNID. INTERN.PEDIATRIA - RETAG",	    "enterpriseId" => "hu"],
    // ["name" => "SAMU",	                            "enterpriseId" => "hu"],
    // ["name" => "MUTIRAO HU",	                    "enterpriseId" => "hu"],
    // ["name" => "NUCLEO DE QUALIDADE",	            "enterpriseId" => "hu"],
    // ["name" => "CUSTOS INDIRETOS",	                "enterpriseId" => "hu"],
    // ["name" => "SEDE GAMP - CENTRO",	            "enterpriseId" => "hu"],
    // ["name" => "UNID. INTERNAÇÃO 7º ANDAR HU",	    "enterpriseId" => "hu"],
    // ["name" => "UNID. INTERNAÇÃO 8º ANDAR HU",	    "enterpriseId" => "hu"],
    // ["name" => "CENTRO CIRÚRGICO HU",	            "enterpriseId" => "hu"],
    // ["name" => "CENTRO OBSTÉTRICO HU",	            "enterpriseId" => "hu"],
    // ["name" => "UNID. SAUDE MENTAL hpscº A HU",	    "enterpriseId" => "hu"],
    // ["name" => "UNID. MATERN 9º A - CONVÊNIOS HU",	    "enterpriseId" => "hu"],
    // ["name" => "UNID. MATERN 9º A - OBST SUS  HU",	    "enterpriseId" => "hu"],
    // ["name" => "UNID. CUIDADOS INTERMEDIÁR 4º A",	    "enterpriseId" => "hu"],
    // ["name" => "UNID. MATERN 9º A- ALOJ.CJ.SUS HU",	"enterpriseId" => "hu"],
    // ["name" => "PACIENTE INTERNO HU",	            "enterpriseId" => "hu"],
    // ["name" => "CLINICA MÉDICA HU",	                "enterpriseId" => "hu"],
    // ["name" => "CLINICA CIRÚRGICA HU",	            "enterpriseId" => "hu"],
    // ["name" => "CLINICA OBSTÉTRICA HU",	            "enterpriseId" => "hu"],
    // ["name" => "CLINICA PEDIÁTRICA HU",	            "enterpriseId" => "hu"],
    // ["name" => "CTI ADULTO HU",	                    "enterpriseId" => "hu"],
    // ["name" => "CTI NEONATAL HU",	                "enterpriseId" => "hu"],
    // ["name" => "CTI PEDIÁTRICA HU",	                "enterpriseId" => "hu"],
    // ["name" => "EMERGÊNCIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "LABORATÓRIO HU",	                "enterpriseId" => "hu"],
    // ["name" => "PATOLOGIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "RADIOLOGIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "DENSITOMETRIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "ECOGRAFIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "CENTRO DE TERAPIA ENDOVASC HU",	    "enterpriseId" => "hu"],
    // ["name" => "MAMOGRAFIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "RESSONÂNCIA MAGNÉTICA HU",	        "enterpriseId" => "hu"],
    // ["name" => "TOMOGRAFIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "AREAS APOIO / ADMINISTRAT HU",	    "enterpriseId" => "hu"],
    // ["name" => "ADMINISTRAÇÃO HU",	                "enterpriseId" => "hu"],
    // ["name" => "FARMACIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "GOVERNANÇA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "MANUTENÇÃO HU",	                    "enterpriseId" => "hu"],
    // ["name" => "NUTRIÇÃO HU",	                    "enterpriseId" => "hu"],
    // ["name" => "AUDIOMETRIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "ENDOSCOPIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "HOSPITAL DIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "NEUROLOGIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "HEMODIÁLISE HU",	                "enterpriseId" => "hu"],
    // ["name" => "LITOTRIPSIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "HEMOTERAPIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "ALMOXARIFADO HU",	                "enterpriseId" => "hu"],
    // ["name" => "SERVIÇOS CIRÚRGICOS HU",	        "enterpriseId" => "hu"],
    // ["name" => "SERVIÇOS DIAGNÓSTICOS HU",	        "enterpriseId" => "hu"],
    // ["name" => "SERVIÇOS DE TRATAMENTO HU",	        "enterpriseId" => "hu"],
    // ["name" => "SERVIÇOS DE INTERNAÇÃO HU",	        "enterpriseId" => "hu"],
    // ["name" => "S.E.G.E.R HU",	                    "enterpriseId" => "hu"],
    // ["name" => "CONSOLIDADO DOS SERVIÇOS HU",	    "enterpriseId" => "hu"],
    // ["name" => "CTI UNID QUEIMADOS HU",	            "enterpriseId" => "hu"],
    // ["name" => "UNID. INTERN.4º A - MÉT.CANG HU",	"enterpriseId" => "hu"],
    // ["name" => "MEDICINA NUCLEAR HU",	            "enterpriseId" => "hu"],
    // ["name" => "CARDIOFISIOLOGIA HU",	            "enterpriseId" => "hu"],
    // ["name" => "FISIOTERAPIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "CONTABILIDADE HU",	                "enterpriseId" => "hu"],
    // ["name" => "CONTROLADORIA HU",	                "enterpriseId" => "hu"],
    // ["name" => "ENSINO HU ( ULBRA )",	            "enterpriseId" => "hu"],
    // ["name" => "FATURAMENTO HU",	                "enterpriseId" => "hu"],
    // ["name" => "FINANCEIRO HU",	                    "enterpriseId" => "hu"],
    // ["name" => "RECURSOS HUMANOS HU",	            "enterpriseId" => "hu"],
    // ["name" => "S.A.M.E HU",	                    "enterpriseId" => "hu"],
    // ["name" => "S.C.I.H HU",	                    "enterpriseId" => "hu"],
    // ["name" => "SERVIÇO DE APOIO AO CLIENTE HU",	"enterpriseId" => "hu"],
    // ["name" => "TECNOLOGIA DA INFORMAÇÃO HU",	    "enterpriseId" => "hu"],
    // ["name" => "TELEFONIA HU",	                    "enterpriseId" => "hu"],
    // ["name" => "SALA DE RECUPER INTERNADO HU",	    "enterpriseId" => "hu"],
    // ["name" => "AMBULATÓRIO HU",	                "enterpriseId" => "hu"],
    // ["name" => "PRONTO ATEND. OBSTÉTRICO HU",	    "enterpriseId" => "hu"],
    // ["name" => "UNID. INTERNAÇÃO PEDIATRIA HU",	    "enterpriseId" => "hu"],
    // ["name" => "NEUROFISIOLOGIA HU",	            "enterpriseId" => "hu"],
    // ["name" => "FONOAUDIOLOGIA HU",	                "enterpriseId" => "hu"],
    ["name" => "UNID. INTERNAÇÃO 10º ANDAR HU",     "enterpriseId" => "hu"],
    ["name" => "SERVIÇO DE PSICOLOGIA HU",          "enterpriseId" => "hu"],
    ["name" => "AMB. GEST. DE ALTO RISCO HU",       "enterpriseId" => "hu"],
    // ["name" => "CONSOLIDADO DOS SERVIÇOS UPA",	    "enterpriseId" => "upa-rio-branco"],
    // ["name" => "SERVIÇOS AMBULATORIAIS UPA",	    "enterpriseId" => "upa-rio-branco"],
    // ["name" => "EMERGÊNCIA UPA",	                "enterpriseId" => "upa-rio-branco"],
    // ["name" => "SERVIÇOS DE DIAGNÓSTICO UPA",	    "enterpriseId" => "upa-rio-branco"],
    // ["name" => "LABORATÓRIO UPA",	                "enterpriseId" => "upa-rio-branco"],
    // ["name" => "RADIOLOGIA UPA",	                "enterpriseId" => "upa-rio-branco"],
    // ["name" => "ÁREAS DE APOIO - ADMINIST UPA",	    "enterpriseId" => "upa-rio-branco"],
    // ["name" => "ADMINISTRAÇÃO UPA",	                "enterpriseId" => "upa-rio-branco"],
    // ["name" => "FARMÁCIA UPA",	                    "enterpriseId" => "upa-rio-branco"],
    // ["name" => "GOVERNANÇA UPA",	                "enterpriseId" => "upa-rio-branco"],
    // ["name" => "MANUTENÇÃO UPA",	                "enterpriseId" => "upa-rio-branco"],
    // ["name" => "NUTRIÇÃO UPA",	                    "enterpriseId" => "upa-rio-branco"],
    // ["name" => "ELETROCARDIOGRAMA UPA",	            "enterpriseId" => "upa-rio-branco"],
    // ["name" => "HOSP. PRONTO SOCORRO CANOAS UP",	"enterpriseId" => "upa-rio-branco"],
];

$enterpriseRepository = $model->em->getRepository('HospitalApi\Entity\Enterprise');
$bossSectorRepository = $model->em->getRepository('HospitalApi\Entity\BossSector');
$bossSector = $bossSectorRepository->find(1);

foreach ($sectors as $sector) {
    $enterprise = $enterpriseRepository->find($sector["enterpriseId"]);

    $sector = new Sector($enterprise, $bossSector, $sector["name"]);
    $model->insert($sector);
}